### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by corycook** [corycook/express-delayed-response#2]
Getting an error seemingly randomly:

```
_http_outgoing.js:371
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (/Users/corycook/Documents/genesis/genesis-ui-api/node_modules/express/lib/response.js:719:10)
    at ServerResponse.response.(anonymous function).args [as set] (/Users/corycook/Documents/genesis/genesis-ui-api/node_modules/express-delayed-response/index.js:48:39)
    at ServerResponse.json (/Users/corycook/Documents/genesis/genesis-ui-api/node_modules/express/lib/response.js:247:10)
    at ServerResponse.response.(anonymous function).args [as json] (/Users/corycook/Documents/genesis/genesis-ui-api/node_modules/express-delayed-response/index.js:48:39)
    at Timeout.setTimeout [as _onTimeout] (/Users/corycook/Documents/genesis/genesis-ui-api/node_modules/express-delayed-response/index.js:71:34)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by corycook** [comment]
This was resolved in 0.3.2 (I should really start making PRs)
